# SPDX-FileCopyrightText: 2025 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: AGPL-3.0-only
# Generated by Django 5.1.4 on 2025-02-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="slideshow",
            name="slideshow_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.DeleteModel(
            name="Slide",
        ),
    ]
