# SPDX-FileCopyrightText: 2025 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: AGPL-3.0-only
# Generated by Django 5.1.4 on 2025-02-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_userextended"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userextended",
            name="language_preference",
            field=models.CharField(default="en", max_length=255),
        ),
    ]
