# SPDX-FileCopyrightText: 2025 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: AGPL-3.0-only
# Generated by Django 5.1.4 on 2025-02-20 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_slideshow_slideshow_data_delete_slide"),
        ("app", "0003_alter_userextended_language_preference"),
    ]

    operations = []
