# SPDX-FileCopyrightText: 2025 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: AGPL-3.0-only
# Generated by Django 5.1.4 on 2025-02-23 19:46
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_merge_20250220_0321"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(upload_to="uploads/"),
        ),
    ]
