# SPDX-FileCopyrightText: 2025 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: AGPL-3.0-only
# Generated by Django 5.1.4 on 2025-02-25 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_document_file"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserExtended",
        ),
    ]
