# SPDX-FileCopyrightText: 2025 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: AGPL-3.0-only
# Generated by Django 5.1.4 on 2025-03-04 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_userextended"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="displaywebsitegroup",
            name="suborganisation",
        ),
        migrations.RemoveField(
            model_name="document",
            name="suborganisation",
        ),
        migrations.RemoveField(
            model_name="slideshow",
            name="suborganisation",
        ),
        migrations.RemoveField(
            model_name="slideshowplaylist",
            name="suborganisation",
        ),
        migrations.AlterField(
            model_name="organisationmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("org_admin", "Organisation Admin"),
                    ("suborg_admin", "Suborganisation Admin"),
                    ("branch_admin", "Branch Admin"),
                    ("employee", "Employee"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "suborganisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="app.suborganisation",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="displaywebsite",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="organisationmembership",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="displaywebsite",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="display_websites",
                to="app.branch",
            ),
        ),
        migrations.AddField(
            model_name="displaywebsitegroup",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="display_website_groups",
                to="app.branch",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="app.branch",
            ),
        ),
        migrations.AddField(
            model_name="organisationmembership",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="app.branch",
            ),
        ),
        migrations.AddField(
            model_name="slideshow",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manage_content",
                to="app.branch",
            ),
        ),
        migrations.AddField(
            model_name="slideshowplaylist",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="playlists",
                to="app.branch",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="displaywebsite",
            unique_together={("name", "branch")},
        ),
        migrations.AlterUniqueTogether(
            name="organisationmembership",
            unique_together={("user", "organisation", "suborganisation", "branch")},
        ),
        migrations.RemoveField(
            model_name="displaywebsite",
            name="suborganisation",
        ),
    ]
