# SPDX-FileCopyrightText: 2025 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: AGPL-3.0-only
# Generated by Django 5.1.4 on 2025-03-05 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_remove_displaywebsitegroup_suborganisation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="slideshowplayerapikey",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: If set, this API key can only be used for one specific branch.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.branch",
            ),
        ),
        migrations.DeleteModel(
            name="ExternalAPIKey",
        ),
    ]
