# SPDX-FileCopyrightText: 2025 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: AGPL-3.0-only
# Generated by Django 5.1.4 on 2025-03-06 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_slideshowplayerapikey_branch_delete_externalapikey"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="displaywebsitegroup",
            name="default_content",
        ),
        migrations.RemoveField(
            model_name="scheduledcontent",
            name="slideshow_playlist",
        ),
        migrations.AddField(
            model_name="displaywebsitegroup",
            name="default_playlist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_playlist_groups",
                to="app.slideshowplaylist",
            ),
        ),
        migrations.AddField(
            model_name="displaywebsitegroup",
            name="default_slideshow",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_slideshow_groups",
                to="app.slideshow",
            ),
        ),
        migrations.AddField(
            model_name="scheduledcontent",
            name="playlist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scheduled_playlists",
                to="app.slideshowplaylist",
            ),
        ),
        migrations.AddField(
            model_name="scheduledcontent",
            name="slideshow",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scheduled_slideshows",
                to="app.slideshow",
            ),
        ),
    ]
