# SPDX-FileCopyrightText: 2025 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: AGPL-3.0-only
# Generated by Django 5.1.4 on 2025-03-09 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_auto_20250307_2107"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="slideshow",
            name="mode",
            field=models.CharField(
                choices=[("slideshow", "Slideshow"), ("interactive", "Interactive")],
                default="slideshow",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="slideshowplayerapikey",
            name="branch",
            field=models.OneToOneField(
                help_text="This API key is automatically tied to the branch.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_key",
                to="app.branch",
            ),
        ),
        migrations.AddField(
            model_name="slideshow",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manage_content",
                to="app.category",
            ),
        ),
        migrations.AddField(
            model_name="slideshow",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="manage_content", to="app.tag"
            ),
        ),
    ]
