# SPDX-FileCopyrightText: 2025 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: AGPL-3.0-only
# Generated by Django 5.1.4 on 2025-04-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_slidetemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledcontent",
            name="combine_with_default",
            field=models.BooleanField(default=False),
        ),
    ]
