# SPDX-FileCopyrightText: 2025 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: AGPL-3.0-only
# Generated by Django 5.1.4 on 2025-04-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_branchurlcollectionitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("PDF", "Pdf"),
                    ("PNG", "Png"),
                    ("JPEG", "Jpeg"),
                    ("SVG", "Svg"),
                    ("GIF", "Gif"),
                    ("MP4", "Mp4"),
                    ("WebP", "Webp"),
                    ("WebM", "Webm"),
                    ("Other", "Other"),
                ],
                default="Other",
                editable=False,
                max_length=10,
            ),
        ),
    ]
