# SPDX-FileCopyrightText: 2025 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: AGPL-3.0-only
# Generated by Django 5.1.4 on 2025-04-16 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_document_file_type"),
        ("app", "0017_documentcategory"),
    ]

    operations = []
