# SPDX-FileCopyrightText: 2025 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: AGPL-3.0-only
# Generated by Django 5.1.4 on 2025-04-23 13:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_document_category_document_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("pdf", "Pdf"),
                    ("png", "Png"),
                    ("jpeg", "Jpeg"),
                    ("svg", "Svg"),
                    ("gif", "Gif"),
                    ("mp4", "Mp4"),
                    ("WebP", "Webp"),
                    ("WebM", "Webm"),
                    ("Other", "Other"),
                ],
                default="Other",
                editable=False,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                max_length=100,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
    ]
