# SPDX-FileCopyrightText: 2025 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: AGPL-3.0-only
# Generated by Django 5.1.4 on 2025-05-04 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_alter_document_file_type_alter_tag_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("hexValue", models.CharField(max_length=7)),
                (
                    "type",
                    models.CharField(
                        choices=[("primary", "Primary"), ("secondary", "Secondary")],
                        default="secondary",
                        max_length=10,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_colors",
                        to="app.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["organisation", "type", "name"],
                "unique_together": {("organisation", "name")},
            },
        ),
    ]
