# SPDX-FileCopyrightText: 2025 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: AGPL-3.0-only
# Generated by Django 5.1.4 on 2025-05-04 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_customcolor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customcolor",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app.organisation",
            ),
        ),
        migrations.AlterField(
            model_name="customcolor",
            name="type",
            field=models.CharField(
                choices=[
                    ("primary", "Primary"),
                    ("secondary", "Secondary"),
                    ("accent", "Accent"),
                    ("background", "Background"),
                    ("text", "Text"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="CustomFont",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Font family name (e.g., 'Roboto', 'Open Sans')",
                        max_length=100,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="URL to the font file (e.g., WOFF, WOFF2, TTF)",
                        max_length=512,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_fonts",
                        to="app.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["organisation", "name"],
                "unique_together": {("organisation", "name")},
            },
        ),
    ]
