# SPDX-FileCopyrightText: 2025 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: AGPL-3.0-only
# Generated by Django 5.1.4 on 2025-05-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_alter_customcolor_organisation_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customfont",
            options={
                "verbose_name": "Custom Font",
                "verbose_name_plural": "Custom Fonts",
            },
        ),
        migrations.RemoveField(
            model_name="customfont",
            name="url",
        ),
        migrations.AddField(
            model_name="customfont",
            name="font_url",
            field=models.URLField(
                default="https://tmpfiles.org/27092983/meslolgsnfbold.ttf",
                help_text="URL to the font file (e.g., WOFF2, TTF)",
                max_length=500,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customfont",
            name="name",
            field=models.CharField(
                help_text="Name of the font (e.g., 'Roboto Slab')", max_length=100
            ),
        ),
    ]
