# SPDX-FileCopyrightText: 2025 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: AGPL-3.0-only
# Generated by Django 5.1.4 on 2025-05-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0023_alter_customfont_options_remove_customfont_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledcontent",
            name="description",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
