# SPDX-FileCopyrightText: 2025 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: AGPL-3.0-only
# Generated by Django 5.1.4 on 2025-06-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0025_category_organisation_tag_organisation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="slidetemplate",
            name="accepted_aspect_ratios",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of supported aspect ratios, e.g. ["16:9","4:3","9:16"]',
            ),
        ),
    ]
