# SPDX-FileCopyrightText: 2025 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: AGPL-3.0-only
# Generated by Django 5.1.4 on 2025-06-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0026_slidetemplate_accepted_aspect_ratios"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slideshow",
            name="isCustomDimensions",
            field=models.BooleanField(default=True),
        ),
    ]
