# SPDX-FileCopyrightText: 2025 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: AGPL-3.0-only
# Generated by Django 5.1.4 on 2025-06-15 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0027_alter_slideshow_iscustomdimensions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisationmembership",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="app.organisation",
            ),
        ),
        migrations.AlterField(
            model_name="organisationmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("org_admin", "Organisation Admin"),
                    ("suborg_admin", "Suborganisation Admin"),
                    ("branch_admin", "Branch Admin"),
                    ("employee", "Employee"),
                ],
                max_length=20,
            ),
        ),
    ]
