# SPDX-FileCopyrightText: 2025 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: AGPL-3.0-only
# Generated by Django 5.2.5 on 2025-08-14 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0028_alter_organisationmembership_organisation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringScheduledContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        help_text="Day of the week (0=Monday, 6=Sunday)",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(help_text="Start time for the recurring event"),
                ),
                (
                    "end_time",
                    models.TimeField(help_text="End time for the recurring event"),
                ),
                ("combine_with_default", models.BooleanField(default=False)),
                (
                    "description",
                    models.CharField(blank=True, max_length=2048, null=True),
                ),
                (
                    "active_from",
                    models.DateField(
                        help_text="Date from which this recurring event is active"
                    ),
                ),
                (
                    "active_until",
                    models.DateField(
                        blank=True,
                        help_text="Date until which this recurring event is active (leave blank for indefinite)",
                        null=True,
                    ),
                ),
                (
                    "display_website_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.displaywebsitegroup",
                    ),
                ),
                (
                    "playlist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_scheduled_playlists",
                        to="app.slideshowplaylist",
                    ),
                ),
                (
                    "slideshow",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_scheduled_slideshows",
                        to="app.slideshow",
                    ),
                ),
            ],
        ),
    ]
