# SPDX-FileCopyrightText: 2025 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: AGPL-3.0-only
# Generated by Django 5.2.5 on 2025-09-05 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0030_add_updated_at_to_slideshow_and_playlist"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegisteredSlideTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slide_type_id",
                    models.IntegerField(
                        help_text="Integer ID that matches a hardcoded slide type in the external system"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for this slide type",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of this slide type",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registered_slide_types",
                        to="app.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registered Slide Type",
                "verbose_name_plural": "Registered Slide Types",
                "ordering": ["slide_type_id"],
                "unique_together": {("organisation", "slide_type_id")},
            },
        ),
    ]
