# SPDX-FileCopyrightText: 2025 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: AGPL-3.0-only
# Generated by Django 5.2.5 on 2025-09-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0031_registeredslidetypes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registeredslidetypes",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Human-readable name for this slide type",
                max_length=255,
                null=True,
            ),
        ),
    ]
