# SPDX-FileCopyrightText: 2025 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: AGPL-3.0-only
# Generated by Django 5.2.5 on 2025-09-08 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0033_wayfinding"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganisationAPIAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_name",
                    models.CharField(
                        choices=[
                            ("winkas", "WinKAS"),
                            ("kmd", "KMD"),
                            ("speedadmin", "SpeedAdmin"),
                        ],
                        help_text="The external API this organisation has access to",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this API access is currently active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_access",
                        to="app.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organisation API Access",
                "verbose_name_plural": "Organisation API Access",
                "unique_together": {("organisation", "api_name")},
            },
        ),
    ]
