# SPDX-FileCopyrightText: 2025 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: AGPL-3.0-only
# Generated by Django 5.2.5 on 2025-09-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0034_organisationapiaccess"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registeredslidetypes",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Human-readable name for this slide type (auto-populated from choices if not provided)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="registeredslidetypes",
            name="slide_type_id",
            field=models.IntegerField(
                choices=[
                    (1, "DDB Events API"),
                    (3, "Newsfeed with Image"),
                    (4, "Dreambroker"),
                    (5, "Newsticker"),
                    (6, "Speed Admin"),
                    (7, "Clock"),
                    (8, "DR Streams"),
                    (9, "KMD Foreningsportalen"),
                    (10, "Frontdesk LTK Borgerservice"),
                    (11, "WinKAS"),
                ],
                help_text="Slide type that matches the frontend slide type system",
            ),
        ),
    ]
